### ISSUE TITLE
Ascii codec can't encode characters in many pulls

### ISSUE THREAD

**Issue by shaun10** [compjour/search-script-scrape#2]
Happens with query #100 The California city whose city manager earns the most total wage per population of its city in 2012

Also with query 83 and a few others.

Do you think it would be helpful to make a PR to update some of the scripts to fix some of these UnicodeEncodeErrors?

**Comment by dannguyen** [comment]
Which version of Python are you using?

**Comment by shaun10** [comment]
2.7.10 OS X 10.11

UnicodeEncodeError: 'ascii' codec can't encode character u'\xa0' in position 57: ordinal not in range(128)

**Comment by theodorp** [comment]
Since you're using python 2, and these were written in python 3, you're going to have to make some changes. For script 83, you need to change the line 

> txt = requests.get(url).text

to return a str instead of unicode, which is as easy as changing ".text" to something else.

And for script 100, after the line

> rows = zfile.read(fname).decode('latin-1').splitlines()

you're left with a list of unicode values, so you need to convert each value to str (I just used a list comprehension and was able to get the script to work).

If you don't want to change the scripts, you can just install python 3 and the unicode errors will be gone

**Comment by shaun10** [comment]
Thanks Theodor will try fix tonight.
